/**
 * generated by Xtext 2.15.0
 */
package org.muml.uppaal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UppaalXMLUiModule extends AbstractUppaalXMLUiModule {
  public UppaalXMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
