/*
 * generated by Xtext
 */
package org.muml.uppaal.ui.contentassist

import org.muml.uppaal.ui.contentassist.AbstractUppaalXMLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class UppaalXMLProposalProvider extends AbstractUppaalXMLProposalProvider {
}
