/**
 * generated by Xtext 2.15.0
 */
package org.muml.uppaal.ide;

import org.eclipse.xtext.util.Modules2;
import org.muml.uppaal.UppaalXMLRuntimeModule;
import org.muml.uppaal.UppaalXMLStandaloneSetup;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UppaalXMLIdeSetup extends UppaalXMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    UppaalXMLRuntimeModule _uppaalXMLRuntimeModule = new UppaalXMLRuntimeModule();
    UppaalXMLIdeModule _uppaalXMLIdeModule = new UppaalXMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_uppaalXMLRuntimeModule, _uppaalXMLIdeModule));
  }
}
