/**
 * generated by Xtext 2.15.0
 */
package org.muml.uppaal.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UppaalXMLIdeModule extends AbstractUppaalXMLIdeModule {
}
