/*
 * generated by Xtext
 */
package org.muml.uppaal.trace.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.muml.uppaal.trace.services.DiagnosticTraceGrammarAccess;

import com.google.inject.Inject;

public class DiagnosticTraceParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DiagnosticTraceGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.muml.uppaal.trace.parser.antlr.internal.InternalDiagnosticTraceParser createParser(XtextTokenStream stream) {
		return new org.muml.uppaal.trace.parser.antlr.internal.InternalDiagnosticTraceParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TraceRepository";
	}
	
	public DiagnosticTraceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DiagnosticTraceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
