/*
 * generated by Xtext 2.15.0
 */
package org.muml.uppaal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUppaalXMLScopeProvider extends DelegatingScopeProvider {
}
