/*
 * generated by Xtext
 */
package org.muml.uppaal.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.muml.uppaal.ui.internal.UppaalXMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class UppaalXMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return UppaalXMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return UppaalXMLActivator.getInstance().getInjector(UppaalXMLActivator.ORG_MUML_UPPAAL_UPPAALXML);
	}
	
}
