/*
 * generated by Xtext 2.15.0
 */
package org.muml.uppaal.parser.antlr;

import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.muml.uppaal.parser.antlr.internal.InternalUppaalXMLParser;
import org.muml.uppaal.services.UppaalXMLGrammarAccess;

import com.google.inject.Inject;

public class UppaalXMLParser extends AbstractAntlrParser {

	@Inject
	private UppaalXMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SINGLE_LINE_COMMENT", "RULE_MULTI_LINE_COMMENT");
	}
	

	@Override
	protected InternalUppaalXMLParser createParser(XtextTokenStream stream) {
		return new InternalUppaalXMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "NTA";
	}

	public UppaalXMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UppaalXMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
