/*
 * generated by Xtext
 */
package org.muml.uppaal.serializer;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.muml.uppaal.services.UppaalXMLGrammarAccess;

import com.google.inject.Inject;

@SuppressWarnings("all")
public abstract class AbstractUppaalXMLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected UppaalXMLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Edge_____ColorKeyword_16_0_5_2_0_EqualsSignKeyword_16_0_5_2_1_STRINGTerminalRuleCall_16_0_5_2_2___or___XKeyword_16_0_5_0_0_EqualsSignKeyword_16_0_5_0_1_STRINGTerminalRuleCall_16_0_5_0_2___or___YKeyword_16_0_5_1_0_EqualsSignKeyword_16_0_5_1_1_STRINGTerminalRuleCall_16_0_5_1_2____a;
	protected AbstractElementAlias match_Edge_____ColorKeyword_16_1_5_2_0_EqualsSignKeyword_16_1_5_2_1_STRINGTerminalRuleCall_16_1_5_2_2___or___XKeyword_16_1_5_0_0_EqualsSignKeyword_16_1_5_0_1_STRINGTerminalRuleCall_16_1_5_0_2___or___YKeyword_16_1_5_1_0_EqualsSignKeyword_16_1_5_1_1_STRINGTerminalRuleCall_16_1_5_1_2____a;
	protected AbstractElementAlias match_Edge_____ColorKeyword_16_2_5_2_0_EqualsSignKeyword_16_2_5_2_1_STRINGTerminalRuleCall_16_2_5_2_2___or___XKeyword_16_2_5_0_0_EqualsSignKeyword_16_2_5_0_1_STRINGTerminalRuleCall_16_2_5_0_2___or___YKeyword_16_2_5_1_0_EqualsSignKeyword_16_2_5_1_1_STRINGTerminalRuleCall_16_2_5_1_2____a;
	protected AbstractElementAlias match_Edge_____ColorKeyword_16_3_5_2_0_EqualsSignKeyword_16_3_5_2_1_STRINGTerminalRuleCall_16_3_5_2_2___or___XKeyword_16_3_5_0_0_EqualsSignKeyword_16_3_5_0_1_STRINGTerminalRuleCall_16_3_5_0_2___or___YKeyword_16_3_5_1_0_EqualsSignKeyword_16_3_5_1_1_STRINGTerminalRuleCall_16_3_5_1_2____a;
	protected AbstractElementAlias match_Edge_____ColorKeyword_16_4_5_2_0_EqualsSignKeyword_16_4_5_2_1_STRINGTerminalRuleCall_16_4_5_2_2___or___XKeyword_16_4_5_0_0_EqualsSignKeyword_16_4_5_0_1_STRINGTerminalRuleCall_16_4_5_0_2___or___YKeyword_16_4_5_1_0_EqualsSignKeyword_16_4_5_1_1_STRINGTerminalRuleCall_16_4_5_1_2____a;
	protected AbstractElementAlias match_Edge_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a;
	protected AbstractElementAlias match_Location_SolidusGreaterThanSignKeyword_3_0_or___GreaterThanSignKeyword_3_1_0_LessThanSignSolidusKeyword_3_1_4_LocationKeyword_3_1_5_GreaterThanSignKeyword_3_1_6__;
	protected AbstractElementAlias match_Location_____ColorKeyword_3_1_2_0_5_2_0_EqualsSignKeyword_3_1_2_0_5_2_1_STRINGTerminalRuleCall_3_1_2_0_5_2_2___or___XKeyword_3_1_2_0_5_0_0_EqualsSignKeyword_3_1_2_0_5_0_1_STRINGTerminalRuleCall_3_1_2_0_5_0_2___or___YKeyword_3_1_2_0_5_1_0_EqualsSignKeyword_3_1_2_0_5_1_1_STRINGTerminalRuleCall_3_1_2_0_5_1_2____a;
	protected AbstractElementAlias match_Location_____ColorKeyword_3_1_2_1_5_2_0_EqualsSignKeyword_3_1_2_1_5_2_1_STRINGTerminalRuleCall_3_1_2_1_5_2_2___or___XKeyword_3_1_2_1_5_0_0_EqualsSignKeyword_3_1_2_1_5_0_1_STRINGTerminalRuleCall_3_1_2_1_5_0_2___or___YKeyword_3_1_2_1_5_1_0_EqualsSignKeyword_3_1_2_1_5_1_1_STRINGTerminalRuleCall_3_1_2_1_5_1_2____a;
	protected AbstractElementAlias match_Location_____XKeyword_3_1_1_2_0_0_EqualsSignKeyword_3_1_1_2_0_1_STRINGTerminalRuleCall_3_1_1_2_0_2___or___YKeyword_3_1_1_2_1_0_EqualsSignKeyword_3_1_1_2_1_1_STRINGTerminalRuleCall_3_1_1_2_1_2____a;
	protected AbstractElementAlias match_NTA_XmlVersion10EncodingUtf8Keyword_0_0_or_XmlVersion10EncodingUtf8Keyword_0_1;
	protected AbstractElementAlias match_NTA___LessThanSignKeyword_5_0_ImportsKeyword_5_1_GreaterThanSignKeyword_5_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_5_3_a_LessThanSignSolidusKeyword_5_4_ImportsKeyword_5_5_GreaterThanSignKeyword_5_6__a;
	protected AbstractElementAlias match_NTA___LessThanSignKeyword_8_0_InstantiationKeyword_8_1_GreaterThanSignKeyword_8_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_8_3_a_LessThanSignSolidusKeyword_8_4_InstantiationKeyword_8_5_GreaterThanSignKeyword_8_6__q;
	protected AbstractElementAlias match_Template___LessThanSignKeyword_8_0_ParameterKeyword_8_1_GreaterThanSignKeyword_8_2_LessThanSignSolidusKeyword_8_4_ParameterKeyword_8_5_GreaterThanSignKeyword_8_6__q;
	protected AbstractElementAlias match_Template_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a;
	protected AbstractElementAlias match_TerminatingExpressions_LeftParenthesisKeyword_3_0_a;
	protected AbstractElementAlias match_TerminatingExpressions_LeftParenthesisKeyword_3_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (UppaalXMLGrammarAccess) access;
		match_Edge_____ColorKeyword_16_0_5_2_0_EqualsSignKeyword_16_0_5_2_1_STRINGTerminalRuleCall_16_0_5_2_2___or___XKeyword_16_0_5_0_0_EqualsSignKeyword_16_0_5_0_1_STRINGTerminalRuleCall_16_0_5_0_2___or___YKeyword_16_0_5_1_0_EqualsSignKeyword_16_0_5_1_1_STRINGTerminalRuleCall_16_0_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getColorKeyword_16_0_5_2_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_0_5_2_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_0_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getXKeyword_16_0_5_0_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_0_5_0_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_0_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getYKeyword_16_0_5_1_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_0_5_1_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_0_5_1_2())));
		match_Edge_____ColorKeyword_16_1_5_2_0_EqualsSignKeyword_16_1_5_2_1_STRINGTerminalRuleCall_16_1_5_2_2___or___XKeyword_16_1_5_0_0_EqualsSignKeyword_16_1_5_0_1_STRINGTerminalRuleCall_16_1_5_0_2___or___YKeyword_16_1_5_1_0_EqualsSignKeyword_16_1_5_1_1_STRINGTerminalRuleCall_16_1_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getColorKeyword_16_1_5_2_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_1_5_2_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_1_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getXKeyword_16_1_5_0_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_1_5_0_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_1_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getYKeyword_16_1_5_1_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_1_5_1_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_1_5_1_2())));
		match_Edge_____ColorKeyword_16_2_5_2_0_EqualsSignKeyword_16_2_5_2_1_STRINGTerminalRuleCall_16_2_5_2_2___or___XKeyword_16_2_5_0_0_EqualsSignKeyword_16_2_5_0_1_STRINGTerminalRuleCall_16_2_5_0_2___or___YKeyword_16_2_5_1_0_EqualsSignKeyword_16_2_5_1_1_STRINGTerminalRuleCall_16_2_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getColorKeyword_16_2_5_2_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_2_5_2_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_2_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getXKeyword_16_2_5_0_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_2_5_0_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_2_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getYKeyword_16_2_5_1_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_2_5_1_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_2_5_1_2())));
		match_Edge_____ColorKeyword_16_3_5_2_0_EqualsSignKeyword_16_3_5_2_1_STRINGTerminalRuleCall_16_3_5_2_2___or___XKeyword_16_3_5_0_0_EqualsSignKeyword_16_3_5_0_1_STRINGTerminalRuleCall_16_3_5_0_2___or___YKeyword_16_3_5_1_0_EqualsSignKeyword_16_3_5_1_1_STRINGTerminalRuleCall_16_3_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getColorKeyword_16_3_5_2_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_3_5_2_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_3_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getXKeyword_16_3_5_0_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_3_5_0_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_3_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getYKeyword_16_3_5_1_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_3_5_1_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_3_5_1_2())));
		match_Edge_____ColorKeyword_16_4_5_2_0_EqualsSignKeyword_16_4_5_2_1_STRINGTerminalRuleCall_16_4_5_2_2___or___XKeyword_16_4_5_0_0_EqualsSignKeyword_16_4_5_0_1_STRINGTerminalRuleCall_16_4_5_0_2___or___YKeyword_16_4_5_1_0_EqualsSignKeyword_16_4_5_1_1_STRINGTerminalRuleCall_16_4_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getColorKeyword_16_4_5_2_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_4_5_2_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_4_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getXKeyword_16_4_5_0_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_4_5_0_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_4_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getYKeyword_16_4_5_1_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_16_4_5_1_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_16_4_5_1_2())));
		match_Edge_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getXKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_2_0_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_2_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEdgeAccess().getYKeyword_2_1_0()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getEqualsSignKeyword_2_1_1()), new TokenAlias(false, false, grammarAccess.getEdgeAccess().getSTRINGTerminalRuleCall_2_1_2())));
		match_Location_SolidusGreaterThanSignKeyword_3_0_or___GreaterThanSignKeyword_3_1_0_LessThanSignSolidusKeyword_3_1_4_LocationKeyword_3_1_5_GreaterThanSignKeyword_3_1_6__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getGreaterThanSignKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getLessThanSignSolidusKeyword_3_1_4()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getLocationKeyword_3_1_5()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getGreaterThanSignKeyword_3_1_6())), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSolidusGreaterThanSignKeyword_3_0()));
		match_Location_____ColorKeyword_3_1_2_0_5_2_0_EqualsSignKeyword_3_1_2_0_5_2_1_STRINGTerminalRuleCall_3_1_2_0_5_2_2___or___XKeyword_3_1_2_0_5_0_0_EqualsSignKeyword_3_1_2_0_5_0_1_STRINGTerminalRuleCall_3_1_2_0_5_0_2___or___YKeyword_3_1_2_0_5_1_0_EqualsSignKeyword_3_1_2_0_5_1_1_STRINGTerminalRuleCall_3_1_2_0_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getColorKeyword_3_1_2_0_5_2_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_2_0_5_2_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_2_0_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getXKeyword_3_1_2_0_5_0_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_2_0_5_0_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_2_0_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getYKeyword_3_1_2_0_5_1_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_2_0_5_1_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_2_0_5_1_2())));
		match_Location_____ColorKeyword_3_1_2_1_5_2_0_EqualsSignKeyword_3_1_2_1_5_2_1_STRINGTerminalRuleCall_3_1_2_1_5_2_2___or___XKeyword_3_1_2_1_5_0_0_EqualsSignKeyword_3_1_2_1_5_0_1_STRINGTerminalRuleCall_3_1_2_1_5_0_2___or___YKeyword_3_1_2_1_5_1_0_EqualsSignKeyword_3_1_2_1_5_1_1_STRINGTerminalRuleCall_3_1_2_1_5_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getColorKeyword_3_1_2_1_5_2_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_2_1_5_2_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_2_1_5_2_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getXKeyword_3_1_2_1_5_0_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_2_1_5_0_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_2_1_5_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getYKeyword_3_1_2_1_5_1_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_2_1_5_1_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_2_1_5_1_2())));
		match_Location_____XKeyword_3_1_1_2_0_0_EqualsSignKeyword_3_1_1_2_0_1_STRINGTerminalRuleCall_3_1_1_2_0_2___or___YKeyword_3_1_1_2_1_0_EqualsSignKeyword_3_1_1_2_1_1_STRINGTerminalRuleCall_3_1_1_2_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getXKeyword_3_1_1_2_0_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_1_2_0_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_1_2_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getLocationAccess().getYKeyword_3_1_1_2_1_0()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getEqualsSignKeyword_3_1_1_2_1_1()), new TokenAlias(false, false, grammarAccess.getLocationAccess().getSTRINGTerminalRuleCall_3_1_1_2_1_2())));
		match_NTA_XmlVersion10EncodingUtf8Keyword_0_0_or_XmlVersion10EncodingUtf8Keyword_0_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getNTAAccess().getXmlVersion10EncodingUtf8Keyword_0_0()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getXmlVersion10EncodingUtf8Keyword_0_1()));
		match_NTA___LessThanSignKeyword_5_0_ImportsKeyword_5_1_GreaterThanSignKeyword_5_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_5_3_a_LessThanSignSolidusKeyword_5_4_ImportsKeyword_5_5_GreaterThanSignKeyword_5_6__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getNTAAccess().getLessThanSignKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getImportsKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getGreaterThanSignKeyword_5_2()), new TokenAlias(true, true, grammarAccess.getNTAAccess().getANY_TOKEN_BUT_XML_CLOSEParserRuleCall_5_3()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getLessThanSignSolidusKeyword_5_4()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getImportsKeyword_5_5()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getGreaterThanSignKeyword_5_6()));
		match_NTA___LessThanSignKeyword_8_0_InstantiationKeyword_8_1_GreaterThanSignKeyword_8_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_8_3_a_LessThanSignSolidusKeyword_8_4_InstantiationKeyword_8_5_GreaterThanSignKeyword_8_6__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNTAAccess().getLessThanSignKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getInstantiationKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getGreaterThanSignKeyword_8_2()), new TokenAlias(true, true, grammarAccess.getNTAAccess().getANY_TOKEN_BUT_XML_CLOSEParserRuleCall_8_3()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getLessThanSignSolidusKeyword_8_4()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getInstantiationKeyword_8_5()), new TokenAlias(false, false, grammarAccess.getNTAAccess().getGreaterThanSignKeyword_8_6()));
		match_Template___LessThanSignKeyword_8_0_ParameterKeyword_8_1_GreaterThanSignKeyword_8_2_LessThanSignSolidusKeyword_8_4_ParameterKeyword_8_5_GreaterThanSignKeyword_8_6__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLessThanSignKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getParameterKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getGreaterThanSignKeyword_8_2()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getLessThanSignSolidusKeyword_8_4()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getParameterKeyword_8_5()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getGreaterThanSignKeyword_8_6()));
		match_Template_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a = new AlternativeAlias(true, true, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getXKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getEqualsSignKeyword_2_0_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getSTRINGTerminalRuleCall_2_0_2())), new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getTemplateAccess().getYKeyword_2_1_0()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getEqualsSignKeyword_2_1_1()), new TokenAlias(false, false, grammarAccess.getTemplateAccess().getSTRINGTerminalRuleCall_2_1_2())));
		match_TerminatingExpressions_LeftParenthesisKeyword_3_0_a = new TokenAlias(true, true, grammarAccess.getTerminatingExpressionsAccess().getLeftParenthesisKeyword_3_0());
		match_TerminatingExpressions_LeftParenthesisKeyword_3_0_p = new TokenAlias(true, false, grammarAccess.getTerminatingExpressionsAccess().getLeftParenthesisKeyword_3_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getANY_TOKEN_BUT_XML_CLOSERule())
			return getANY_TOKEN_BUT_XML_CLOSEToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * ANY_TOKEN_BUT_XML_CLOSE:
	 * 	XML_KEYWORDS | XML_ATTRIBUTE_KEYWORDS | XML_STRUCTURE_KEYWORDS |
	 * 	UPPAAL_KEYWORDS | UPPAAL_STRUCTURE_KEYWORDS |
	 * 	STRING | ID | WS | ANY_OTHER | INT | SINGLE_LINE_COMMENT | MULTI_LINE_COMMENT
	 * ;
	 */
	protected String getANY_TOKEN_BUT_XML_CLOSEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "imports";
	}
	
	/**
	 * terminal STRING:
	 * 	'"' ( '\\' . | !('\\'|'"') )* '"' |
	 * 	"'" ( '\\' . | !('\\'|"'") )* "'"
	 * ;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Edge_____ColorKeyword_16_0_5_2_0_EqualsSignKeyword_16_0_5_2_1_STRINGTerminalRuleCall_16_0_5_2_2___or___XKeyword_16_0_5_0_0_EqualsSignKeyword_16_0_5_0_1_STRINGTerminalRuleCall_16_0_5_0_2___or___YKeyword_16_0_5_1_0_EqualsSignKeyword_16_0_5_1_1_STRINGTerminalRuleCall_16_0_5_1_2____a.equals(syntax))
				emit_Edge_____ColorKeyword_16_0_5_2_0_EqualsSignKeyword_16_0_5_2_1_STRINGTerminalRuleCall_16_0_5_2_2___or___XKeyword_16_0_5_0_0_EqualsSignKeyword_16_0_5_0_1_STRINGTerminalRuleCall_16_0_5_0_2___or___YKeyword_16_0_5_1_0_EqualsSignKeyword_16_0_5_1_1_STRINGTerminalRuleCall_16_0_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Edge_____ColorKeyword_16_1_5_2_0_EqualsSignKeyword_16_1_5_2_1_STRINGTerminalRuleCall_16_1_5_2_2___or___XKeyword_16_1_5_0_0_EqualsSignKeyword_16_1_5_0_1_STRINGTerminalRuleCall_16_1_5_0_2___or___YKeyword_16_1_5_1_0_EqualsSignKeyword_16_1_5_1_1_STRINGTerminalRuleCall_16_1_5_1_2____a.equals(syntax))
				emit_Edge_____ColorKeyword_16_1_5_2_0_EqualsSignKeyword_16_1_5_2_1_STRINGTerminalRuleCall_16_1_5_2_2___or___XKeyword_16_1_5_0_0_EqualsSignKeyword_16_1_5_0_1_STRINGTerminalRuleCall_16_1_5_0_2___or___YKeyword_16_1_5_1_0_EqualsSignKeyword_16_1_5_1_1_STRINGTerminalRuleCall_16_1_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Edge_____ColorKeyword_16_2_5_2_0_EqualsSignKeyword_16_2_5_2_1_STRINGTerminalRuleCall_16_2_5_2_2___or___XKeyword_16_2_5_0_0_EqualsSignKeyword_16_2_5_0_1_STRINGTerminalRuleCall_16_2_5_0_2___or___YKeyword_16_2_5_1_0_EqualsSignKeyword_16_2_5_1_1_STRINGTerminalRuleCall_16_2_5_1_2____a.equals(syntax))
				emit_Edge_____ColorKeyword_16_2_5_2_0_EqualsSignKeyword_16_2_5_2_1_STRINGTerminalRuleCall_16_2_5_2_2___or___XKeyword_16_2_5_0_0_EqualsSignKeyword_16_2_5_0_1_STRINGTerminalRuleCall_16_2_5_0_2___or___YKeyword_16_2_5_1_0_EqualsSignKeyword_16_2_5_1_1_STRINGTerminalRuleCall_16_2_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Edge_____ColorKeyword_16_3_5_2_0_EqualsSignKeyword_16_3_5_2_1_STRINGTerminalRuleCall_16_3_5_2_2___or___XKeyword_16_3_5_0_0_EqualsSignKeyword_16_3_5_0_1_STRINGTerminalRuleCall_16_3_5_0_2___or___YKeyword_16_3_5_1_0_EqualsSignKeyword_16_3_5_1_1_STRINGTerminalRuleCall_16_3_5_1_2____a.equals(syntax))
				emit_Edge_____ColorKeyword_16_3_5_2_0_EqualsSignKeyword_16_3_5_2_1_STRINGTerminalRuleCall_16_3_5_2_2___or___XKeyword_16_3_5_0_0_EqualsSignKeyword_16_3_5_0_1_STRINGTerminalRuleCall_16_3_5_0_2___or___YKeyword_16_3_5_1_0_EqualsSignKeyword_16_3_5_1_1_STRINGTerminalRuleCall_16_3_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Edge_____ColorKeyword_16_4_5_2_0_EqualsSignKeyword_16_4_5_2_1_STRINGTerminalRuleCall_16_4_5_2_2___or___XKeyword_16_4_5_0_0_EqualsSignKeyword_16_4_5_0_1_STRINGTerminalRuleCall_16_4_5_0_2___or___YKeyword_16_4_5_1_0_EqualsSignKeyword_16_4_5_1_1_STRINGTerminalRuleCall_16_4_5_1_2____a.equals(syntax))
				emit_Edge_____ColorKeyword_16_4_5_2_0_EqualsSignKeyword_16_4_5_2_1_STRINGTerminalRuleCall_16_4_5_2_2___or___XKeyword_16_4_5_0_0_EqualsSignKeyword_16_4_5_0_1_STRINGTerminalRuleCall_16_4_5_0_2___or___YKeyword_16_4_5_1_0_EqualsSignKeyword_16_4_5_1_1_STRINGTerminalRuleCall_16_4_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Edge_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a.equals(syntax))
				emit_Edge_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Location_SolidusGreaterThanSignKeyword_3_0_or___GreaterThanSignKeyword_3_1_0_LessThanSignSolidusKeyword_3_1_4_LocationKeyword_3_1_5_GreaterThanSignKeyword_3_1_6__.equals(syntax))
				emit_Location_SolidusGreaterThanSignKeyword_3_0_or___GreaterThanSignKeyword_3_1_0_LessThanSignSolidusKeyword_3_1_4_LocationKeyword_3_1_5_GreaterThanSignKeyword_3_1_6__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Location_____ColorKeyword_3_1_2_0_5_2_0_EqualsSignKeyword_3_1_2_0_5_2_1_STRINGTerminalRuleCall_3_1_2_0_5_2_2___or___XKeyword_3_1_2_0_5_0_0_EqualsSignKeyword_3_1_2_0_5_0_1_STRINGTerminalRuleCall_3_1_2_0_5_0_2___or___YKeyword_3_1_2_0_5_1_0_EqualsSignKeyword_3_1_2_0_5_1_1_STRINGTerminalRuleCall_3_1_2_0_5_1_2____a.equals(syntax))
				emit_Location_____ColorKeyword_3_1_2_0_5_2_0_EqualsSignKeyword_3_1_2_0_5_2_1_STRINGTerminalRuleCall_3_1_2_0_5_2_2___or___XKeyword_3_1_2_0_5_0_0_EqualsSignKeyword_3_1_2_0_5_0_1_STRINGTerminalRuleCall_3_1_2_0_5_0_2___or___YKeyword_3_1_2_0_5_1_0_EqualsSignKeyword_3_1_2_0_5_1_1_STRINGTerminalRuleCall_3_1_2_0_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Location_____ColorKeyword_3_1_2_1_5_2_0_EqualsSignKeyword_3_1_2_1_5_2_1_STRINGTerminalRuleCall_3_1_2_1_5_2_2___or___XKeyword_3_1_2_1_5_0_0_EqualsSignKeyword_3_1_2_1_5_0_1_STRINGTerminalRuleCall_3_1_2_1_5_0_2___or___YKeyword_3_1_2_1_5_1_0_EqualsSignKeyword_3_1_2_1_5_1_1_STRINGTerminalRuleCall_3_1_2_1_5_1_2____a.equals(syntax))
				emit_Location_____ColorKeyword_3_1_2_1_5_2_0_EqualsSignKeyword_3_1_2_1_5_2_1_STRINGTerminalRuleCall_3_1_2_1_5_2_2___or___XKeyword_3_1_2_1_5_0_0_EqualsSignKeyword_3_1_2_1_5_0_1_STRINGTerminalRuleCall_3_1_2_1_5_0_2___or___YKeyword_3_1_2_1_5_1_0_EqualsSignKeyword_3_1_2_1_5_1_1_STRINGTerminalRuleCall_3_1_2_1_5_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Location_____XKeyword_3_1_1_2_0_0_EqualsSignKeyword_3_1_1_2_0_1_STRINGTerminalRuleCall_3_1_1_2_0_2___or___YKeyword_3_1_1_2_1_0_EqualsSignKeyword_3_1_1_2_1_1_STRINGTerminalRuleCall_3_1_1_2_1_2____a.equals(syntax))
				emit_Location_____XKeyword_3_1_1_2_0_0_EqualsSignKeyword_3_1_1_2_0_1_STRINGTerminalRuleCall_3_1_1_2_0_2___or___YKeyword_3_1_1_2_1_0_EqualsSignKeyword_3_1_1_2_1_1_STRINGTerminalRuleCall_3_1_1_2_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_NTA_XmlVersion10EncodingUtf8Keyword_0_0_or_XmlVersion10EncodingUtf8Keyword_0_1.equals(syntax))
				emit_NTA_XmlVersion10EncodingUtf8Keyword_0_0_or_XmlVersion10EncodingUtf8Keyword_0_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_NTA___LessThanSignKeyword_5_0_ImportsKeyword_5_1_GreaterThanSignKeyword_5_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_5_3_a_LessThanSignSolidusKeyword_5_4_ImportsKeyword_5_5_GreaterThanSignKeyword_5_6__a.equals(syntax))
				emit_NTA___LessThanSignKeyword_5_0_ImportsKeyword_5_1_GreaterThanSignKeyword_5_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_5_3_a_LessThanSignSolidusKeyword_5_4_ImportsKeyword_5_5_GreaterThanSignKeyword_5_6__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_NTA___LessThanSignKeyword_8_0_InstantiationKeyword_8_1_GreaterThanSignKeyword_8_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_8_3_a_LessThanSignSolidusKeyword_8_4_InstantiationKeyword_8_5_GreaterThanSignKeyword_8_6__q.equals(syntax))
				emit_NTA___LessThanSignKeyword_8_0_InstantiationKeyword_8_1_GreaterThanSignKeyword_8_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_8_3_a_LessThanSignSolidusKeyword_8_4_InstantiationKeyword_8_5_GreaterThanSignKeyword_8_6__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Template___LessThanSignKeyword_8_0_ParameterKeyword_8_1_GreaterThanSignKeyword_8_2_LessThanSignSolidusKeyword_8_4_ParameterKeyword_8_5_GreaterThanSignKeyword_8_6__q.equals(syntax))
				emit_Template___LessThanSignKeyword_8_0_ParameterKeyword_8_1_GreaterThanSignKeyword_8_2_LessThanSignSolidusKeyword_8_4_ParameterKeyword_8_5_GreaterThanSignKeyword_8_6__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Template_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a.equals(syntax))
				emit_Template_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TerminatingExpressions_LeftParenthesisKeyword_3_0_a.equals(syntax))
				emit_TerminatingExpressions_LeftParenthesisKeyword_3_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TerminatingExpressions_LeftParenthesisKeyword_3_0_p.equals(syntax))
				emit_TerminatingExpressions_LeftParenthesisKeyword_3_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     guard=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     selection+=Selection '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     synchronization=SynchronizationLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     target=[Location|STRING] '/>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     update+=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 */
	protected void emit_Edge_____ColorKeyword_16_0_5_2_0_EqualsSignKeyword_16_0_5_2_1_STRINGTerminalRuleCall_16_0_5_2_2___or___XKeyword_16_0_5_0_0_EqualsSignKeyword_16_0_5_0_1_STRINGTerminalRuleCall_16_0_5_0_2___or___YKeyword_16_0_5_1_0_EqualsSignKeyword_16_0_5_1_1_STRINGTerminalRuleCall_16_0_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"synchronisation"' (ambiguity) '>' synchronization=SynchronizationLabel
	 *     guard=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"synchronisation"' (ambiguity) '>' synchronization=SynchronizationLabel
	 *     selection+=Selection '</' 'label' '>' '<' 'label' 'kind' '=' '"synchronisation"' (ambiguity) '>' synchronization=SynchronizationLabel
	 *     synchronization=SynchronizationLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"synchronisation"' (ambiguity) '>' synchronization=SynchronizationLabel
	 *     target=[Location|STRING] '/>' '<' 'label' 'kind' '=' '"synchronisation"' (ambiguity) '>' synchronization=SynchronizationLabel
	 *     update+=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"synchronisation"' (ambiguity) '>' synchronization=SynchronizationLabel
	 */
	protected void emit_Edge_____ColorKeyword_16_1_5_2_0_EqualsSignKeyword_16_1_5_2_1_STRINGTerminalRuleCall_16_1_5_2_2___or___XKeyword_16_1_5_0_0_EqualsSignKeyword_16_1_5_0_1_STRINGTerminalRuleCall_16_1_5_0_2___or___YKeyword_16_1_5_1_0_EqualsSignKeyword_16_1_5_1_1_STRINGTerminalRuleCall_16_1_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"guard"' (ambiguity) '>' guard=Expression
	 *     guard=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"guard"' (ambiguity) '>' guard=Expression
	 *     selection+=Selection '</' 'label' '>' '<' 'label' 'kind' '=' '"guard"' (ambiguity) '>' guard=Expression
	 *     synchronization=SynchronizationLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"guard"' (ambiguity) '>' guard=Expression
	 *     target=[Location|STRING] '/>' '<' 'label' 'kind' '=' '"guard"' (ambiguity) '>' guard=Expression
	 *     update+=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"guard"' (ambiguity) '>' guard=Expression
	 */
	protected void emit_Edge_____ColorKeyword_16_2_5_2_0_EqualsSignKeyword_16_2_5_2_1_STRINGTerminalRuleCall_16_2_5_2_2___or___XKeyword_16_2_5_0_0_EqualsSignKeyword_16_2_5_0_1_STRINGTerminalRuleCall_16_2_5_0_2___or___YKeyword_16_2_5_1_0_EqualsSignKeyword_16_2_5_1_1_STRINGTerminalRuleCall_16_2_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"assignment"' (ambiguity) '>' update+=Expression
	 *     guard=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"assignment"' (ambiguity) '>' update+=Expression
	 *     selection+=Selection '</' 'label' '>' '<' 'label' 'kind' '=' '"assignment"' (ambiguity) '>' update+=Expression
	 *     synchronization=SynchronizationLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"assignment"' (ambiguity) '>' update+=Expression
	 *     target=[Location|STRING] '/>' '<' 'label' 'kind' '=' '"assignment"' (ambiguity) '>' update+=Expression
	 *     update+=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"assignment"' (ambiguity) '>' update+=Expression
	 */
	protected void emit_Edge_____ColorKeyword_16_3_5_2_0_EqualsSignKeyword_16_3_5_2_1_STRINGTerminalRuleCall_16_3_5_2_2___or___XKeyword_16_3_5_0_0_EqualsSignKeyword_16_3_5_0_1_STRINGTerminalRuleCall_16_3_5_0_2___or___YKeyword_16_3_5_1_0_EqualsSignKeyword_16_3_5_1_1_STRINGTerminalRuleCall_16_3_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"select"' (ambiguity) '>' selection+=Selection
	 *     guard=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"select"' (ambiguity) '>' selection+=Selection
	 *     selection+=Selection '</' 'label' '>' '<' 'label' 'kind' '=' '"select"' (ambiguity) '>' selection+=Selection
	 *     synchronization=SynchronizationLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"select"' (ambiguity) '>' selection+=Selection
	 *     target=[Location|STRING] '/>' '<' 'label' 'kind' '=' '"select"' (ambiguity) '>' selection+=Selection
	 *     update+=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"select"' (ambiguity) '>' selection+=Selection
	 */
	protected void emit_Edge_____ColorKeyword_16_4_5_2_0_EqualsSignKeyword_16_4_5_2_1_STRINGTerminalRuleCall_16_4_5_2_2___or___XKeyword_16_4_5_0_0_EqualsSignKeyword_16_4_5_0_1_STRINGTerminalRuleCall_16_4_5_0_2___or___YKeyword_16_4_5_1_0_EqualsSignKeyword_16_4_5_1_1_STRINGTerminalRuleCall_16_4_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '<' 'transition' (ambiguity) '>' '<' 'source' 'ref' '=' source=[Location|STRING]
	 *     (rule start) '<' 'transition' (ambiguity) 'color' '=' colorCode=STRING
	 *     colorCode=STRING (ambiguity) '>' '<' 'source' 'ref' '=' source=[Location|STRING]
	 *     colorCode=STRING (ambiguity) 'color' '=' colorCode=STRING
	 */
	protected void emit_Edge_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '/>' | ('>' '</' 'location' '>')
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '<' 'location' (ambiguity) (rule start)
	 *     colorCode=STRING (ambiguity) (rule end)
	 *     id=STRING (ambiguity) (rule end)
	 *     position=Point (ambiguity) (rule end)
	 */
	protected void emit_Location_SolidusGreaterThanSignKeyword_3_0_or___GreaterThanSignKeyword_3_1_0_LessThanSignSolidusKeyword_3_1_4_LocationKeyword_3_1_5_GreaterThanSignKeyword_3_1_6__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '<' 'location' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     colorCode=STRING '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     id=STRING '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     invariant=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     name=ID '</' 'name' '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 *     position=Point '>' '<' 'label' 'kind' '=' '"comments"' (ambiguity) '>' comment=CommentLabel
	 */
	protected void emit_Location_____ColorKeyword_3_1_2_0_5_2_0_EqualsSignKeyword_3_1_2_0_5_2_1_STRINGTerminalRuleCall_3_1_2_0_5_2_2___or___XKeyword_3_1_2_0_5_0_0_EqualsSignKeyword_3_1_2_0_5_0_1_STRINGTerminalRuleCall_3_1_2_0_5_0_2___or___YKeyword_3_1_2_0_5_1_0_EqualsSignKeyword_3_1_2_0_5_1_1_STRINGTerminalRuleCall_3_1_2_0_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING) | ('color' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '<' 'location' '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 *     colorCode=STRING '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 *     comment=CommentLabel '</' 'label' '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 *     id=STRING '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 *     invariant=Expression '</' 'label' '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 *     name=ID '</' 'name' '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 *     position=Point '>' '<' 'label' 'kind' '=' '"invariant"' (ambiguity) '>' invariant=Expression
	 */
	protected void emit_Location_____ColorKeyword_3_1_2_1_5_2_0_EqualsSignKeyword_3_1_2_1_5_2_1_STRINGTerminalRuleCall_3_1_2_1_5_2_2___or___XKeyword_3_1_2_1_5_0_0_EqualsSignKeyword_3_1_2_1_5_0_1_STRINGTerminalRuleCall_3_1_2_1_5_0_2___or___YKeyword_3_1_2_1_5_1_0_EqualsSignKeyword_3_1_2_1_5_1_1_STRINGTerminalRuleCall_3_1_2_1_5_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '<' 'location' '>' '<' 'name' (ambiguity) '>' name=ID
	 *     colorCode=STRING '>' '<' 'name' (ambiguity) '>' name=ID
	 *     id=STRING '>' '<' 'name' (ambiguity) '>' name=ID
	 *     position=Point '>' '<' 'name' (ambiguity) '>' name=ID
	 */
	protected void emit_Location_____XKeyword_3_1_1_2_0_0_EqualsSignKeyword_3_1_1_2_0_1_STRINGTerminalRuleCall_3_1_1_2_0_2___or___YKeyword_3_1_1_2_1_0_EqualsSignKeyword_3_1_1_2_1_1_STRINGTerminalRuleCall_3_1_1_2_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '<?xml version="1.0" encoding="utf-8"?>' | '<?xml version='1.0' encoding='utf-8'?>'
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         (rule start) 
	 *         (ambiguity) 
	 *         '<!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'http://www.it.uu.se/research/group/darts/uppaal/flat-1_1.dtd'>' 
	 *         '<' 
	 *         'nta' 
	 *         '>' 
	 *         ('<' 'imports' '>' ANY_TOKEN_BUT_XML_CLOSE* '</' 'imports' '>')* 
	 *         '<' 
	 *         'declaration' 
	 *         '>' 
	 *         globalDeclarations=GlobalDeclarations
	 *     )
	 *     (
	 *         (rule start) 
	 *         (ambiguity) 
	 *         '<!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'http://www.it.uu.se/research/group/darts/uppaal/flat-1_1.dtd'>' 
	 *         '<' 
	 *         'nta' 
	 *         '>' 
	 *         ('<' 'imports' '>' ANY_TOKEN_BUT_XML_CLOSE* '</' 'imports' '>')* 
	 *         '<' 
	 *         'template' 
	 *         '>' 
	 *         template+=Template
	 *     )
	 */
	protected void emit_NTA_XmlVersion10EncodingUtf8Keyword_0_0_or_XmlVersion10EncodingUtf8Keyword_0_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         '<' 
	  *         'imports' 
	  *         '>' 
	  *         ANY_TOKEN_BUT_XML_CLOSE* 
	  *         '</' 
	  *         'imports' 
	  *         '>'
	  *     )*
	 *
	 * This ambiguous syntax occurs at:
	 *     (
	 *         (rule start) 
	 *         ('<?xml version="1.0" encoding="utf-8"?>' | '<?xml version='1.0' encoding='utf-8'?>') 
	 *         '<!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'http://www.it.uu.se/research/group/darts/uppaal/flat-1_1.dtd'>' 
	 *         '<' 
	 *         'nta' 
	 *         '>' 
	 *         (ambiguity) 
	 *         '<' 
	 *         'declaration' 
	 *         '>' 
	 *         globalDeclarations=GlobalDeclarations
	 *     )
	 *     (
	 *         (rule start) 
	 *         ('<?xml version="1.0" encoding="utf-8"?>' | '<?xml version='1.0' encoding='utf-8'?>') 
	 *         '<!DOCTYPE nta PUBLIC '-//Uppaal Team//DTD Flat System 1.1//EN' 'http://www.it.uu.se/research/group/darts/uppaal/flat-1_1.dtd'>' 
	 *         '<' 
	 *         'nta' 
	 *         '>' 
	 *         (ambiguity) 
	 *         '<' 
	 *         'template' 
	 *         '>' 
	 *         template+=Template
	 *     )
	 */
	protected void emit_NTA___LessThanSignKeyword_5_0_ImportsKeyword_5_1_GreaterThanSignKeyword_5_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_5_3_a_LessThanSignSolidusKeyword_5_4_ImportsKeyword_5_5_GreaterThanSignKeyword_5_6__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         '<' 
	  *         'instantiation' 
	  *         '>' 
	  *         ANY_TOKEN_BUT_XML_CLOSE* 
	  *         '</' 
	  *         'instantiation' 
	  *         '>'
	  *     )?
	 *
	 * This ambiguous syntax occurs at:
	 *     template+=Template '</' 'template' '>' (ambiguity) '<' 'system' '>' systemDeclarations=SystemDeclarations
	 */
	protected void emit_NTA___LessThanSignKeyword_8_0_InstantiationKeyword_8_1_GreaterThanSignKeyword_8_2_ANY_TOKEN_BUT_XML_CLOSEParserRuleCall_8_3_a_LessThanSignSolidusKeyword_8_4_InstantiationKeyword_8_5_GreaterThanSignKeyword_8_6__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         '<' 
	  *         'parameter' 
	  *         '>' 
	  *         '</' 
	  *         'parameter' 
	  *         '>'
	  *     )?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '</' 'name' '>' (ambiguity) '<' 'declaration' '>' declarations=LocalDeclarations
	 *     name=ID '</' 'name' '>' (ambiguity) location+=Location
	 */
	protected void emit_Template___LessThanSignKeyword_8_0_ParameterKeyword_8_1_GreaterThanSignKeyword_8_2_LessThanSignSolidusKeyword_8_4_ParameterKeyword_8_5_GreaterThanSignKeyword_8_6__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (('x' '=' STRING) | ('y' '=' STRING))*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '<' 'name' (ambiguity) '>' name=ID
	 */
	protected void emit_Template_____XKeyword_2_0_0_EqualsSignKeyword_2_0_1_STRINGTerminalRuleCall_2_0_2___or___YKeyword_2_1_0_EqualsSignKeyword_2_1_1_STRINGTerminalRuleCall_2_1_2____a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' negatedExpression=IncrementDecrementExpression
	 *     (rule start) (ambiguity) 'not' negatedExpression=AssignmentExpression
	 *     (rule start) (ambiguity) function=[Function|UPPAAL_IDENTIFIER]
	 *     (rule start) (ambiguity) identifier=[NamedElement|UPPAAL_TYPE_OR_IDENTIFIER]
	 *     (rule start) (ambiguity) operator=DecrementOperator
	 *     (rule start) (ambiguity) operator=IncrementOperator
	 *     (rule start) (ambiguity) quantifier=Quantifier
	 *     (rule start) (ambiguity) text=LiteralExpressionText
	 *     (rule start) (ambiguity) {ArithmeticExpression.firstExpr=}
	 *     (rule start) (ambiguity) {AssignmentExpression.firstExpr=}
	 *     (rule start) (ambiguity) {BitShiftExpression.firstExpr=}
	 *     (rule start) (ambiguity) {BitwiseExpression.firstExpr=}
	 *     (rule start) (ambiguity) {CompareExpression.firstExpr=}
	 *     (rule start) (ambiguity) {ConditionExpression.ifExpression=}
	 *     (rule start) (ambiguity) {IncrementDecrementExpression.expression=}
	 *     (rule start) (ambiguity) {LogicalExpression.firstExpr=}
	 *     (rule start) (ambiguity) {MinMaxExpression.firstExpr=}
	 *     (rule start) (ambiguity) {ScopedIdentifierExpression.scope=}
	 */
	protected void emit_TerminatingExpressions_LeftParenthesisKeyword_3_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' negatedExpression=IncrementDecrementExpression
	 *     (rule start) (ambiguity) 'not' negatedExpression=AssignmentExpression
	 *     (rule start) (ambiguity) operator=DecrementOperator
	 *     (rule start) (ambiguity) operator=IncrementOperator
	 *     (rule start) (ambiguity) quantifier=Quantifier
	 *     (rule start) (ambiguity) {ArithmeticExpression.firstExpr=}
	 *     (rule start) (ambiguity) {AssignmentExpression.firstExpr=}
	 *     (rule start) (ambiguity) {BitShiftExpression.firstExpr=}
	 *     (rule start) (ambiguity) {BitwiseExpression.firstExpr=}
	 *     (rule start) (ambiguity) {CompareExpression.firstExpr=}
	 *     (rule start) (ambiguity) {ConditionExpression.ifExpression=}
	 *     (rule start) (ambiguity) {IncrementDecrementExpression.expression=}
	 *     (rule start) (ambiguity) {LogicalExpression.firstExpr=}
	 *     (rule start) (ambiguity) {MinMaxExpression.firstExpr=}
	 *     (rule start) (ambiguity) {ScopedIdentifierExpression.scope=}
	 */
	protected void emit_TerminatingExpressions_LeftParenthesisKeyword_3_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
