/*
 * generated by Xtext
 */
package org.muml.uppaal;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UppaalXMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return org.muml.uppaal.ui.internal.UppaalXMLActivator.getInstance().getInjector("org.muml.uppaal.UppaalXML");
	}

}
