/*
 * generated by Xtext
 */
package org.muml.uppaal.trace.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DiagnosticTraceUiModule extends org.muml.uppaal.trace.ui.AbstractDiagnosticTraceUiModule {
	public DiagnosticTraceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
